# Generated by Django 2.0.4 on 2018-04-25 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_confirmation',
            field=models.BooleanField(default=False),
        ),
    ]
